<?php

// Exit if accessed directly
if ( !defined( 'ABSPATH' ) ) {
	exit;
}

/**
 *
 * WARNING: Please do not edit this file in any way
 *
 * load the theme function files
 */

$template_directory = get_template_directory();

require( $template_directory . '/core/includes/functions.php' );
require( $template_directory . '/core/includes/functions-update.php' );
require( $template_directory . '/core/includes/functions-sidebar.php' );
require( $template_directory . '/core/includes/functions-install.php' );
require( $template_directory . '/core/includes/functions-admin.php' );
require( $template_directory . '/core/includes/functions-extras.php' );
require( $template_directory . '/core/includes/functions-extentions.php' );
require( $template_directory . '/core/includes/theme-options/theme-options.php' );
require( $template_directory . '/core/includes/post-custom-meta.php' );
require( $template_directory . '/core/includes/tha-theme-hooks.php' );
require( $template_directory . '/core/includes/hooks.php' );
require( $template_directory . '/core/includes/version.php' );
require( $template_directory . '/core/includes/upsell/theme-upsell.php' );
require( $template_directory . '/core/includes/customizer.php' );

// Return value of the supplied responsive free theme option.
function responsive_free_get_option( $option, $default = false ) {
	global $responsive_options;

	// If the option is set then return it's value, otherwise return false.
	if ( isset( $responsive_options[$option] ) ) {
		return $responsive_options[$option];
	}

	return $default;
}
function responsive_free_setup() {
   add_theme_support( 'title-tag' );
}
add_action( 'after_setup_theme', 'responsive_free_setup' );

if ( ! function_exists( '_wp_render_title_tag' ) ) :
    function responsive_free_render_title() {
?>
<title><?php wp_title( '|', true, 'right' ); ?></title>
<?php
    }
    add_action( 'wp_head', 'responsive_free_render_title' );
endif;

function example_customizer($wp_customize){
	$wp_customize->add_section(
		'example_section_one',
		array(
			'title' => 'Example Settings',
			'description' => 'This is a settings section.',
			'priority' => 200,
		)
	);
	$wp_customize->add_setting(
		'copyright_textbox',
		array(
			'default' => 'Default copyright text',
		)
	);
	$wp_customize->add_control(
		'copyright_textbox',
		array(
			'label' => 'Copyright text',
			'section' => 'example_section_one',
			'type' => 'text',
		)

	);
	$wp_customize->add_setting(
		'hide_copyright'

	);
	$wp_customize->add_control(
		'hide_copyright',
		array(
			'type' =>'checkbox',
			'label'=>'Hide Copyright text',
			'section' => 'example_section_one'
		)

	);

	$wp_customize->add_setting(
		'logo_placement',
		array(
			'default' => 'left',
		)
	);
	$wp_customize->add_control(
		'logo_placement',
		array(
			'type' => 'radio',
			'label' => 'Logo placement',
			'section' => 'example_section_one',
			'choices' => array(
				'left' => 'Left',
				'right' => 'Right',
				'center' => 'Center',
			),
		)
	);
	$wp_customize->add_setting(
		'powered_by',
		array(
			'default' => 'wordpress',
		)
	);

	$wp_customize->add_control(
		'powered_by',
		array(
			'type' => 'select',
			'label' => 'This site is powered by:',
			'section' => 'example_section_one',
			'choices' => array(
				'wordpress' => 'WordPress',
				'hamsters' => 'Hamsters',
				'jet-fuel' => 'Jet Fuel',
				'nuclear-energy' => 'Nuclear Energy',
			),
		)
	);
}
add_action('customize_register','example_customizer');

add_action('wp_head','logo_position');

function logo_position() {
	$example_position = get_theme_mod( 'logo_placement' );
	if ( $example_position != '' ) {
		switch ( $example_position ) {
			case 'left':
				// Do nothing. The theme already aligns the logo to the left
				break;
			case 'right':
				echo '<style type="text/css">';
				echo '#header #logo{ float: right; }';
				echo '</style>';
				break;
			case 'center':
				echo '<style type="text/css">';
				echo '#header{ text-align: center; }';
				echo '#header #logo{ float: none; margin-left: auto; margin-right: auto; }';
				echo '</style>';
				break;
		}
	}
}

